[project]
name = "daemon"
version = "0.1.0"
description = "Simple daemon example"
authors = ["Hadrien Mary <hadrien.mary@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "python clock_daemon.py --name clock1 -n 5 --sleep 1"
start2 = "python clock_daemon.py --name clock2 -n 5 --sleep 1"

[dependencies]
python = ">=3.12.1,<3.13"
