[project]
name = "jupyterlab"
version = "0.1.0"
description = "Jupyter Lab examples"
authors = ["Ruben Arts <ruben@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
start = "jupyter lab --no-browser --log-level CRITICAL"
test = "echo 'No tests yet'"

[dependencies]
jupyterlab = "4.*"
numpy = "1.25.*"
matplotlib = "3.*"
sympy = "1.12.*"
scipy = "1.11.*"
scikit-learn = "1.*"
ipywidgets = "8.*"
ipython = "8.*"
# Install pip to allow users to install pip packages after the server is started.
pip = "23.2.*"
